import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/middleware/providers";
import { Roboto_Condensed, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto_Condensed({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`bg-background ${robotoSans.variable} ${jetBrainsMono.variable} antialiased`}
        >
          <Toaster position="top-center" />
          {children}
        </body>
      </html>
    </Providers>
  );
}
