openapi: 3.0.0
info:
  title: Social Media Backend API
  description: API untuk aplikasi media sosial, mencakup autentikasi dan manajemen user.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Development Server

components:
  schemas:
    $ref: "./models.yaml"
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
  parameters:
    pageParam:
      name: page
      in: query
      description: "Nomor halaman (mulai dari 1)."
      schema:
        type: integer
        default: 1
    limitParam:
      name: limit
      in: query
      description: "Jumlah item per halaman."
      schema:
        type: integer
        default: 10
    searchParam:
      name: search
      in: query
      description: "Keyword pencarian untuk username atau fullname."
      schema:
        type: string

paths:
  $ref: "./paths.yaml"

security:
  - cookieAuth: []